### ISSUE TITLE
VM does not save after build

### ISSUE THREAD

**Issue by mcaulifn** [cirruslabs/packer-plugin-tart#61] opened 2023-04-27 14:34 UTC
The past 10 or so builds have not saved after finishing. I can't find anything to indicate why it might fail to save.

```
==> base.tart-cli.base: Provisioning with shell script: /var/folders/zz/5pds_n8j1q98bg_dlbtm6r2c0000gn/T/packer-shell195630698
==> base.tart-cli.base: Gracefully shutting down the VM...
==> base.tart-cli.base: Waiting for the tart process to exit...
Build 'base.tart-cli.base' finished after 1 hour 34 minutes.

==> Wait completed after 1 hour 34 minutes

==> Builds finished. The artifacts of successful builds are:
--> base.tart-cli.base: macos-12.6

% tart list <table formatted for readability>
| Source | Name | Size | Running |
| local | macos-12.6-4a74327b-cf71-4dcf-bb22-c5fafe0f2777 | 45 | true |
| oci | xxx.dkr.ecr.us-west-2.amazonaws.com/macos-12.6:latest | 300 | false |
| oci | xxx.dkr.ecr.us-west-2.amazonaws.com/macos-12.6@sha256:shaxxx | 300 | false |
| oci | ghcr.io/cirruslabs/macos-monterey-base:latest | 40 | false |
| oci | ghcr.io/cirruslabs/macos-monterey-base@sha256:77a2fbbf0e533200cb6b5585bbc0898e6f7f8aadd0e6e385fd0ea86b0bb2a9b4                  40 | false |
```

**Comment by fkorotkov** [comment] 2023-04-27 14:52
Which version of the plugin are you using? Could you please also share your `source` block for the VM? Lastly, are you overriding `TART_HOME` by any change?

**Comment by mcaulifn** [comment] 2023-04-27 16:09
I changed the name and tried again:

```
==> Builds finished. The artifacts of successful builds are:
--> base.tart-cli.base: macos-12.6-test
% tart list
Source Name Size Running
local  macos-12.6-test 70   false
oci    916370655143.dkr.ecr.us-west-2.amazonaws.com/macos-12.6:latest 300  false

% tart push macos-12.6-test xxx.dkr.ecr.us-west-2.amazonaws.com/macos-12.6:latest --chunk-size 15 --populate-cache
the specified VM "macos-12.6-test" does not exist

% tart list
Source Name Size Running
local  macos-12.6-f8ba557b-7222-4393-85f5-55fcb80531bd

**Comment by mcaulifn** [comment] 2023-04-27 16:19
I had a second build going on a different instance. I was able to do a quick clone. I can run the vm, but I cannot push it up to ECR. Not sure if this is a cause or a symptom of cloning while it was being deleted.

```
% tart push testtest 916370655143.dkr.ecr.us-west-2.amazonaws.com/macos-12.6:latest --chunk-size 15 --populate-cache
pushing testtest to xxxx.dkr.ecr.us-west-2.amazonaws.com/macos-12.6:latest...
pushing config...
pushing disk... this will take a while...
0%
Error: UnexpectedHTTPStatusCode(when: "streaming blob to https://xxx.dkr.ecr.us-west-2.amazonaws.com/v2/macos-12.6/blobs/uploads/guid", code: 416, details: "{\"errors\":[{\"code\":\"BLOB_UPLOAD_INVALID\",\"message\":\"First byte of the layer part is 300
00000 instead of 25485760\"}]}\n")
```

**Comment by fkorotkov** [comment] 2023-04-27 19:03
I wasn't able to reproduce with [our templates](https://github.com/cirruslabs/macos-image-templates) and it's hard to diagnose without seeing your code. Does seem like either some cleanup script removes it or `TART_HOME` is overridden so when you run in terminal there is nothing to be found.

**Comment by mcaulifn** [comment] 2023-04-27 19:11
What should `TART_HOME` be set to? I don't see it set at all right now.

**Comment by fkorotkov** [comment] 2023-04-27 20:03
Ideally it shouldn't be set but some people prefer to store all the VMs on external drives and point `TART_HOME` to it. By default, Tart stores everything in `~/.tart`.

**Comment by fkorotkov** [comment] 2023-05-04 17:45
Closing since it seems like a setup issue rather than something that can be done on Tart side.

**Closed by fkorotkov** 2023-05-04 17:45 UTC
